package ${packageName}.service;
import java.util.*;
import ${packageName}.jooq.common.generated.tables.records.*;
import javax.annotation.Generated;

@Generated(
    value = {
        "https://github.com/coolcooldee/sloth",
        "Sloth version:1.0"
    },
    comments = "This class is generated by Sloth"
)
public interface ${upperFirstLetterName}Service{


	Integer count();

    ${upperFirstLetterName}Record getById(Long id);

	List<${upperFirstLetterName}Record> list();

}