package ${packageName}.service;
import java.util.*;
import ${packageName}.jooq.common.generated.tables.records.*;
import javax.annotation.Generated;

@Generated(
    value = {
        "https://github.com/coolcooldee/sloth",
        "sloth version:1.0"
    },
    comments = "This class is generated by sloth"
)
public interface ${upperFirstLetterName}Service{


	Integer count();

    ${jooqName}Record getBy${upperFirstLetterPrimaryKey}(${primaryKeyType} ${primaryKey});

	List<${jooqName}Record> list();

}