package ${packageName}.service;
import java.util.*;
import ${packageName}.model.${upperFirstLetterName};
import ${packageName}.common.Page;

/**
 * This is generated by Sloth.
 * ${upperFirstLetterName}
 */
public interface ${upperFirstLetterName}Service{

	Integer save(${upperFirstLetterName} ${lowerFirstLetterName});

	Integer count();

	${upperFirstLetterName} getById(Object id);

	void deleteById(Object id);

	void update(${upperFirstLetterName} ${lowerFirstLetterName});

	List<${upperFirstLetterName}> list();

	Page<${upperFirstLetterName}> page(int pageNo, int pageSize);


}