package ${packageName}.controller.restfulapi;

import java.util.*;
import ${packageName}.model.${upperFirstLetterName};
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import ${packageName}.service.${upperFirstLetterName}Service;
import ${packageName}.common.Page;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

/**
* This is generated by RKiller.
*/
@RestController
@EnableSwagger2
@RequestMapping(value = "/${lowerFirstLetterName}")
public class ${upperFirstLetterName}Controller {

	@Autowired
	private ${upperFirstLetterName}Service ${lowerFirstLetterName}Service;

	@RequestMapping(value = "/test", method = RequestMethod.GET)
	public String test(${upperFirstLetterName} ${lowerFirstLetterName}) {
		return "success";
	}

	@RequestMapping(value = "/save", method = RequestMethod.POST)
	public void save(${upperFirstLetterName} ${lowerFirstLetterName}) {
		${lowerFirstLetterName}Service.save(${lowerFirstLetterName});
	}

	@RequestMapping(value = "/delete/{id}", method = RequestMethod.POST)
	public void  delete(@PathVariable Object id) {
		${lowerFirstLetterName}Service.deleteById(id);
	}

	@RequestMapping(value = "/view/{id}", method = RequestMethod.GET)
	public ${upperFirstLetterName}  view(@PathVariable Object id) {
		return ${lowerFirstLetterName}Service.getById(id);
	}

	@RequestMapping(value = "/update", method = RequestMethod.POST)
	public void update(${upperFirstLetterName} ${lowerFirstLetterName}) {
		${lowerFirstLetterName}Service.update(${lowerFirstLetterName});
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	public Integer  count() {
		return ${lowerFirstLetterName}Service.count();
	}

	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public List<${upperFirstLetterName}> list() {
		return ${lowerFirstLetterName}Service.list();
	}

	@RequestMapping(value = "/page", method = RequestMethod.GET)
	public Page<${upperFirstLetterName}> page(@RequestParam int pageNo, @RequestParam int pageSize) {
		return ${lowerFirstLetterName}Service.page(pageNo, pageSize);
	}

}
