package ${packageName}.service;
import java.util.*;
import ${packageName}.model.${upperFirstLetterName};
import ${packageName}.common.Page;

/**
 * This is generated by Sloth.
 * ${upperFirstLetterName}
 */
public interface ${upperFirstLetterName}Service{

	/**
	*  保存${upperFirstLetterName}
	*/
	Integer save(${upperFirstLetterName} ${lowerFirstLetterName});

	/**
	*  获取${upperFirstLetterName}的数量
	*/
	Integer count();

	/**
	* 根据主键查询
	*/
	${upperFirstLetterName} getById(Object id);

	/**
	* 根据主键删除
	*/
	void deleteById(Object id);

	/**
	* 根据主键更新
	*/
	void update(${upperFirstLetterName} ${lowerFirstLetterName});

	/**
	* 查看列表(最多10个)
	*/
	List<${upperFirstLetterName}> list();

	/**
	* 分页查找
	*/
	Page<${upperFirstLetterName}> page(int pageNo, int pageSize);

	/**
	* 查找auto increment
	*/
	Integer increment();

}