package ${packageName}.service.impl;
import java.util.*;
import ${packageName}.jooq.common.generated.tables.records.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.jooq.DSLContext;
import ${packageName}.service.${upperFirstLetterName}Service;
import ${packageName}.jooq.common.generated.tables.${upperFirstLetterName};
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
@Service
public  class ${upperFirstLetterName}ServiceImpl implements ${upperFirstLetterName}Service{

	@Autowired
	private DSLContext dslContext;

	@Override
	public ${upperFirstLetterName}Record getById(Long id){
		return dslContext.selectFrom(${upperFirstLetterName}.${upperName}).where(${upperFirstLetterName}.${upperName}.ID.equals(id)).limit(1).fetchOne();
	}

	@Override
	public Integer count(){
	    return 0;
	}

	@Override
	public List<${upperFirstLetterName}Record> list(){
		return null;
	}
	
}