package ${packageName}.service.impl;
import java.util.*;
import ${packageName}.jooq.common.generated.tables.records.*;
import ${packageName}.jooq.common.generated.tables.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.jooq.DSLContext;
import org.jooq.Field;
import ${packageName}.service.${jooqName}Service;

/**
* ${name}
* This is generated by Sloth.
*/
@Service
public  class ${jooqName}ServiceImpl implements ${jooqName}Service{

	@Autowired
	private DSLContext dslContext;

	@Override
	public ${jooqName}Record getById(Integer id){

        //${jooqName} temp = new ${jooqName}();
		//return dslContext.selectFrom(temp).where(temp.ID.in(id)).limit(1).fetchOne();
		return null;
	}

	@Override
	public Integer count(){
	    return 0;
	}

	@Override
	public List<${jooqName}Record> list(){
		return null;
	}
	
}