package ${packageName}.service;
import java.util.*;
import ${packageName}.jooq.common.generated.tables.records.*;
import ${packageName}.jooq.common.generated.tables.*;
import org.jooq.Field;

/**
 * This is generated by RKiller.
 * ${jooqName}
 */
public interface ${jooqName}Service{

	/**
	*  获取${jooqName}Record的数量
	*/
	public Integer count();

	/**
	* 根据主键查询(唯一)
	*/
	public ${jooqName}Record getById(Integer id);

	/**
	* 查看列表(最多10个)
	*/
	public List<${jooqName}Record> list();

}