package ${packageName}.service;
import java.util.*;
import ${packageName}.jooq.common.generated.tables.records.*;
import ${packageName}.jooq.common.generated.tables.*;
import org.jooq.Field;

/**
 * This is generated by Sloth.
 * ${jooqName}
 */
public interface ${jooqName}Service{


	public Integer count();


	public ${jooqName}Record getById(Integer id);


	public List<${jooqName}Record> list();

}