package ${packageName}.model;

import javax.annotation.Generated;

/**
 * This class is generated by Sloth.
 * ${name}
 */
@Generated(
	value = {
	"http://www.xxxxx.org",
	"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public class ${upperFirstLetterName} {

	<#list columns as column>
	/**
	   ${column.remark}
	 */
	private ${column.type} ${column.name};
	
	</#list>
		

	<#list columns as column>
	
	public ${column.type} get<#if column.name?index_of("_") gt -1>${column.name}<#else>${column.upperFirstLetterName}</#if>() {
		return ${column.name};
	}

	public void set<#if column.name?index_of("_") gt -1>${column.name}<#else>${column.upperFirstLetterName}</#if>(${column.type} ${column.name}) {
		this.${column.name} = ${column.name};
	} 
	</#list>
	
	<#--public Page getPage() {-->
		<#--return pagetemplate;-->
	<#--}-->
	<#--public void setPage(Page pagetemplate) {-->
		<#--this.pagetemplate = pagetemplate;-->
	<#--}-->
}
