package ${packageName}.repository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import ${packageName}.model.${upperFirstLetterName};
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"sloth version:1.0"
	},
	comments = "This class is generated by sloth"
)
@Repository
public interface ${upperFirstLetterName}Repository extends JpaRepository<${upperFirstLetterName}, ${primaryKeyType}> {

}
