package ${packageName}.repository;
import java.util.*;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;
import ${packageName}.model.${upperFirstLetterName};
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
@Repository
public interface ${upperFirstLetterName}Repository extends PagingAndSortingRepository<${upperFirstLetterName}, Long> {

}
