package ${packageName}.controller;

import org.springframework.web.bind.annotation.*;
import springfox.documentation.annotations.ApiIgnore;
import javax.annotation.Generated;

@Generated(
	value = {
		"https://github.com/coolcooldee/sloth",
		"sloth version:1.0"
	},
	comments = "This class is generated by sloth"
)
@RestController
@ApiIgnore
public class IndexController {

	@RequestMapping(value={"/","/index"},method=RequestMethod.GET)
	public String index() {
		return "Congratulations. Your Application Is Available, <a href='/apis-docs-by-sloth.html'>Apis</a>";
	}

}
