package ${packageName}.model;

import javax.annotation.Generated;

/**
 * This class is generated by Sloth.
 * ${name}
 */
@Generated(
	value = {
	"http://www.xxxxx.org",
	"Sloth version:1.0"
	},
	comments = "This class is generated by Sloth"
)
public class ${upperFirstLetterName} {

	<#list columns as column>
	/**
	   ${column.remark}
	 */
	private ${column.type} ${column.lowerFirstLetterName};
	
	</#list>
		
	//分页
	<#--private Page pagetemplate;-->
	
	
	 <#--字段的get和set -->
	<#list columns as column>
	
	public ${column.type} get${column.upperFirstLetterName}() {
		return ${column.lowerFirstLetterName};
	}

	public void set${column.upperFirstLetterName}(${column.type} ${column.lowerFirstLetterName}) {
		this.${column.lowerFirstLetterName} = ${column.lowerFirstLetterName};
	} 
	</#list>
	
	<#--public Page getPage() {-->
		<#--return pagetemplate;-->
	<#--}-->
	<#--public void setPage(Page pagetemplate) {-->
		<#--this.pagetemplate = pagetemplate;-->
	<#--}-->
}
